spring.datasource.url=jdbc:postgresql://localhost:5432/gestionpatient
spring.datasource.password=postgres
spring.datasource.username=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.mvc.view.prefix=/templates/
spring.mvc.view.suffix=.html

spring.thymeleaf.encoding=UTF-8

